apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistants
spec:
  selector:
    matchLabels:
      app: home
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home-assistants
        image: homeassistant/raspberrypi3-homeassistant:stable
        volumeMounts:
        - mountPath: /config
          name: ha-config
        ports:
        - containerPort: 8123
      volumes:
      - name: ha-config
        hostPath: 
          path: /usr/share/hassio
          type: Directory
      nodeSelector:
        node: "master-rpi"
